### ISSUE TITLE
Error in Bcbar.py

### ISSUE THREAD

**Issue by fgiacomozzi** [jonathanrjpereira/Bitcoin-Bar#1]
Hi, after a regular use of the script, now i got this error. I've not modified the file
I run the script on a Pi3
  **File "bcbar.py", line 33, in <module>
    disp[x] = data[x] + " " + data[x+1].replace(',','') #Each element of disp is the Name of the parameter & its value. The commas present in the values have been removed for better displaying asthetics
IndexError: list assignment index out of range**
Thank you
Franco

**Comment by jonathanrjpereira** [comment]
Hi @fgiacomozzi 
I have made some updates to the files. This should fix the issue you were facing. 
Please let me know if the system works now.

I have also seen that there may be some new real-time data parameters that may appear like:
- Current activated soft forks
- Current pending soft forks
- Next retarget period block height
- Blocks to mine until next difficulty retarget
- Next difficulty retarget ETA

Please let me know if your Bitcoin Bar is displaying these parameters too.

**Comment by fgiacomozzi** [comment]
Hi Jonathan
Thank you so much
Everything now works perfectly. Also new parameters are working
Have a nice day
Franco



Il giorno dom 3 mag 2020 alle ore 18:15 Jonathan Pereira <
notifications@github.com> ha scritto:
