### ISSUE TITLE
Line 34 Error. Cannot retrieve data.

### ISSUE THREAD

**Issue by rotaryfurball** [jonathanrjpereira/Bitcoin-Bar#3]
An error on line 34. Must be with the new updated website it is grabbing from. Please take a look @jonathanrjpereira 

if data [x+1] == None
IndexError: list index out of range

**Comment by jonathanrjpereira** [comment]
Hi @rotaryfurball 

It looks like the website from which the data is being scraped has implemented some sort of Cloudfare protection which doesn't allow the program to gather the data. 

The only way to fix this is to use a free API instead of web-scraping.

I will begin to look for API's that provide such functionality. If you have any suggestions for free API's with data stats that you would like to see, feel free to leave a comment below. 

Once I have successfully, integrated an API for retrieving the data, I will let you know so that you and other Bitcoin Bar users can test it too and give feedback. This will take a couple of weeks to figure out so stay tuned.

**Comment by rotaryfurball** [comment]
> Hi @rotaryfurball
> 
> It looks like the website from which the data is being scraped has implemented some sort of Cloudfare protection which doesn't allow the program to gather the data.
> 
> The only way to fix this is to use a free API instead of web-scraping.
> 
> I will begin to look for API's that provide such functionality. If you have any suggestions for free API's with data stats that you would like to see, feel free to leave a comment below.
> 
> Once I have successfully, integrated an API for retrieving the data, I will let you know so that you and other Bitcoin Bar users can test it too and give feedback. This will take a couple of weeks to figure out so stay tuned.

Hello @jonathanrjpereira ,

Yes, please. It seems that CoinGecko has the best API currently. I will attempt writing a fix for this, but my knowledge of python is nowhere near your skill level. So, please do attempt it aswell.

**Comment by rotaryfurball** [comment]
@jonathanrjpereira I eventually figured out daisy chain error.

**Comment by tmlee** [comment]
Hey @jonathanrjpereira @rotaryfurball , noticed this discussion and saw that you might have some issue with pulling bitcoin price data. May I recommend trying out the CoinGecko API. You can easily grab it with this endpoint

https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd,eur,gbp,jpy

I am happy to answer any questions you may have as well regarding the API. Cheers!

**Comment by jonathanrjpereira** [comment]
@tmlee Does Coingecko have an API to retrieve data **Stats** like those available on the website: https://www.bitcoinblockhalf.com/ ?

**Comment by tmlee** [comment]
> @tmlee Does Coingecko have an API to retrieve data **Stats** like those available on the website: https://www.bitcoinblockhalf.com/ ?

Currently, we do not yet have those information. In any case for on-chain metrics, we fetch it from our data partners or third party services.

**Comment by rotaryfurball** [comment]
> @tmlee Does Coingecko have an API to retrieve data **Stats** like those available on the website: https://www.bitcoinblockhalf.com/ ?

Hey Jonathan, any updates?

**Comment by jonathanrjpereira** [comment]
I still haven't found a free API that can give me all the stats.

**Comment by rotaryfurball** [comment]
> I still haven't found a free API that can give me all the stats.

Can you implement just the price API?

**Comment by TLA020** [comment]
I'm not a Python Developer, but created a simpel script that fetches the data from an API.

I Created a Pullrequest.
#6 
@jonathanrjpereira @rotaryfurball

**Comment by jonathanrjpereira** [comment]
![image](https://user-images.githubusercontent.com/10046350/119700632-75885800-be21-11eb-9802-0e14bb8adfbd.png)
It seems like this web scrapping method is still working.
