### ISSUE TITLE
How to increase web request limit?

### ISSUE THREAD

**Issue by CobreDev** [jonathanrjpereira/Bitcoin-Bar#8]
This is probably me being dumb, but I can't seem to figure out how to increase the rate that data is pulled. I'm using this mostly for a display of the price, so updating every 1hr isn't the greatest for this case.

**Comment by jonathanrjpereira** [comment]
Right now we scrape from the website: [www.bitcoinblockhalf.com](www.bitcoinblockhalf.com). The update rate is dependent upon on how often the website updates the data fields.

**Comment by CobreDev** [comment]
Ah, didn’t realize it was based on the website. Thanks!
